name: Random Number CA 
on:
  release:
    types: [published]
    tag:
    - v0.*

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    
    steps:

      # https://github.com/marketplace/actions/checkout
      #his action checks-out repository under $GITHUB_WORKSPACE, so that workflow can access it
      - name: Checkout the code from github repo
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/docker-login
      #To login to docker account 
      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      # https://github.com/marketplace/actions/build-and-push-docker-images
      #Buld and push with image tag as <account name>/<image name>:<tag> format
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .          
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/randomnum/${{ github.ref }}

      